"""empty message

Revision ID: 0de495e9c1d6
Revises: d2ef73b50fa0
Create Date: 2021-09-30 23:03:33.866792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de495e9c1d6'
down_revision = 'd2ef73b50fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_email_key', 'tenant', type_='unique')
    op.drop_constraint('tenant_fob_key', 'tenant', type_='unique')
    op.drop_constraint('tenant_name_key', 'tenant', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tenant_name_key', 'tenant', ['name'])
    op.create_unique_constraint('tenant_fob_key', 'tenant', ['fob'])
    op.create_unique_constraint('tenant_email_key', 'tenant', ['email'])
    # ### end Alembic commands ###
