"""empty message

Revision ID: 2cd57bef50dd
Revises: f08ec2b20f8f
Create Date: 2021-09-06 23:44:10.400738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd57bef50dd'
down_revision = 'f08ec2b20f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tenant', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant', type_='foreignkey')
    op.drop_column('tenant', 'owner_id')
    # ### end Alembic commands ###
