"""empty message

Revision ID: 33a88605c848
Revises: 2cd57bef50dd
Create Date: 2021-09-07 23:00:00.568868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a88605c848'
down_revision = '2cd57bef50dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('fob', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'tenant', ['fob'])
    op.drop_constraint('tenant_owner_id_fkey', 'tenant', type_='foreignkey')
    op.drop_column('tenant', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tenant_owner_id_fkey', 'tenant', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'tenant', type_='unique')
    op.drop_column('tenant', 'fob')
    # ### end Alembic commands ###
