"""empty message

Revision ID: c5517be10695
Revises: f19a556c7bf9
Create Date: 2021-09-18 15:09:01.826856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5517be10695'
down_revision = 'f19a556c7bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_manager')
    # ### end Alembic commands ###
