"""empty message

Revision ID: f19a556c7bf9
Revises: ff4a5a403a09
Create Date: 2021-09-12 02:26:04.476880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19a556c7bf9'
down_revision = 'ff4a5a403a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('number', sa.String(length=120), nullable=False))
    op.drop_constraint('unit_name_key', 'unit', type_='unique')
    op.create_unique_constraint(None, 'unit', ['number'])
    op.drop_column('unit', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'unit', type_='unique')
    op.create_unique_constraint('unit_name_key', 'unit', ['name'])
    op.drop_column('unit', 'number')
    # ### end Alembic commands ###
