"""empty message

Revision ID: ff4a5a403a09
Revises: 33a88605c848
Create Date: 2021-09-10 00:46:42.270025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4a5a403a09'
down_revision = '33a88605c848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('phone', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'tenant', ['phone'])
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    op.drop_constraint(None, 'tenant', type_='unique')
    op.drop_column('tenant', 'phone')
    # ### end Alembic commands ###
